global ROBOT_BASE_LVEL_LOW 
global ROBOT_BASE_LVEL_HIGH
global ROBOT_BASE_RVEL_LOW
global ROBOT_BASE_RVEL_HIGH
global ROBOT_RADIUS
global SIM_TIMESTEP

ROBOT_BASE_LVEL_LOW  = 1.7  # mm/s
ROBOT_BASE_LVEL_HIGH = 5.0  # mm/s
ROBOT_BASE_RVEL_LOW  = 2.75 # deg/s
ROBOT_BASE_RVEL_HIGH = 3.75 # deg/s
ROBOT_RADIUS = 22
SIM_TIMESTEP = 1000./60